# Generated by Django 3.0.3 on 2020-02-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('security_code', models.CharField(max_length=256)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(default='Indonesia', max_length=256)),
                ('phone', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('npwp', models.CharField(blank=True, max_length=256, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('board', models.CharField(blank=True, max_length=200, null=True)),
                ('business_field', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=256, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=256, null=True)),
                ('registrar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('position', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicrectors', to='api.CompanyInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateSecretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaries', to='api.CompanyInfo')),
            ],
        ),
    ]
